# Generated by Django 4.2.30 on 2026-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_banner_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_gradient',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('sunset', 'Sunset'), ('forest', 'Forest'), ('crimson', 'Crimson'), ('slate', 'Slate'), ('aurora', 'Aurora'), ('rose', 'Rose'), ('teal', 'Teal')], default='blue', max_length=20),
        ),
    ]
