# Generated by Django 4.2.30 on 2026-08-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_show_login_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pref_compact_tables',
            field=models.BooleanField(default=False, help_text='Denser rows and tighter spacing on data tables.', verbose_name='Compact Tables'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_large_text',
            field=models.BooleanField(default=False, help_text='Increase the base font size across the app.', verbose_name='Large Text'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_reduce_effects',
            field=models.BooleanField(default=False, help_text='Disable glass blur and animated background effects for better performance.', verbose_name='Reduce Visual Effects'),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_reduce_motion',
            field=models.BooleanField(default=False, help_text='Disable entrance animations and smooth scrolling.', verbose_name='Reduce Motion'),
        ),
    ]
