# Generated by Django 4.2 on 2025-11-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0002_statuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='backup_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'engineer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
