# Generated by Django 4.2.11 on 2025-11-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_request_backup_engineer"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
