# Generated by Django 4.2.30 on 2026-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_sqr_tracker_full_columns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestcommunication',
            new_name='hub_request_request_4c5451_idx',
            old_name='hub_request_request__b23575_idx',
        ),
        migrations.AlterField(
            model_name='engineeractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('learning', 'Learning'), ('internal_support', 'Internal Support'), ('on_call_support', 'On-Call Support'), ('pre_sales', 'Pre-Sales'), ('project_management', 'Project Management'), ('training', 'Training'), ('deployment', 'Deployment')], default='internal_support', max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='product_category',
            field=models.CharField(choices=[('Azure', 'Azure'), ('M365', 'M365'), ('VMware', 'VMware'), ('Omnissa', 'Omnissa'), ('Hybrid', 'Hybrid'), ('Dell', 'Dell'), ('HP', 'HP'), ('Network', 'Network'), ('Others', 'Others')], max_length=50),
        ),
    ]
