# Generated by Django 4.2.30 on 2026-05-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0031_add_veeam_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['engineer', 'on_hold', 'pm_esg']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
