# Generated by Django 4.2.30 on 2026-08-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0039_sqrsubmissionhistory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sqrsubmissionhistory",
            new_name="hub_sqrsubm_submiss_60e348_idx",
            old_name="hub_sqrhist_submiss_9d3a4d_idx",
        ),
        migrations.RenameIndex(
            model_name="sqrsubmissionhistory",
            new_name="hub_sqrsubm_actor_i_ca88f6_idx",
            old_name="hub_sqrhist_actor_i_75f42a_idx",
        ),
        migrations.RenameIndex(
            model_name="sqrsubmissionhistory",
            new_name="hub_sqrsubm_action_828c70_idx",
            old_name="hub_sqrhist_action__3528de_idx",
        ),
    ]
