# Generated by Django 5.2.17 on 2026-09-21 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0046_notification_toast_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SqrProjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish Date (Actual)')),
                ('status', models.CharField(choices=[('pending_start', 'Pending Start'), ('ongoing', 'Ongoing'), ('at_risk', 'At Risk'), ('closed', 'Closed')], default='pending_start', max_length=20)),
                ('percent_complete', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_action_remarks', models.TextField(blank=True)),
                ('folder_link', models.URLField(blank=True)),
                ('schedule_health', models.CharField(choices=[('ok', 'OK'), ('at_risk', 'At Risk'), ('over', 'Over')], default='ok', max_length=20)),
                ('scope_health', models.CharField(choices=[('ok', 'OK'), ('at_risk', 'At Risk'), ('over', 'Over')], default='ok', max_length=20)),
                ('budget_health', models.CharField(choices=[('ok', 'OK'), ('at_risk', 'At Risk'), ('over', 'Over')], default='ok', max_length=20)),
                ('recovery_action_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqr_performance_managed', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='hub.sqrsubmission')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
