ACCOUNT_MANAGERS = [
    {"name": "Aileen B. Gutierrez", "email": "AileenG@phildata.com"},
    {"name": "Anabelle D. Alapide", "email": "AnabelleA@phildata.com"},
    {"name": "Charisse P. Plata", "email": "CharriseP@phildata.com"},
    {"name": "Christine Joy A. Fabros", "email": "ChristineF@phildata.com"},
    {"name": "Elisha Jeimarie S. Tañada", "email": "ElishaJ@phildata.com"},
    {"name": "Jimlyn Espinosa", "email": "JimlynE@phildata.com"},
    {"name": "Kevin Dela Cruz", "email": "KevinDC@phildata.com"},
    {"name": "Kristel Camill V. Roldan", "email": "KristelR@phildata.com"},
    {"name": "Leonarda G. Lucena", "email": "LeonardaL@phildata.com"},
    {"name": "Manilyn Villaflores", "email": "ManilynV@phildata.com"},
    {"name": "Marvin I. San Miguel", "email": "MarvinSM@phildata.com"},
    {"name": "Mica Ella R. Labindao", "email": "MicaL@phildata.com"},
    {"name": "Orly N. Palomar, Jr.", "email": "Orlyp@phildata.com"},
    {"name": "Reennalyn F. Ortilano", "email": "ReennalynO@phildata.com"},
    {"name": "Rowell C. De Leon", "email": "RowellDL@phildata.com"},
]

ACCOUNT_MANAGER_NAMES = [manager["name"] for manager in ACCOUNT_MANAGERS]

ENGINEERS = [
    {"name": "Airoll Ross M. Santos", "email": "AirollS@phildata.com"},
    {"name": "Aldwin B. Banta", "email": "AldwinB@phildata.com"},
    {"name": "Archie Gerard U. Arengo", "email": "ArchieA@phildata.com"},
    {"name": "Christian Noel Claveria", "email": "ChristianOC@phildata.com"},
    {"name": "Errolyn S. Encontro", "email": "ErrolynE@phildata.com"},
    {"name": "Ferdinand D. Geli", "email": "FerdinandG@phildata.com"},
    {"name": "Francis Buensalida", "email": "FrancisB@phildata.com"},
    {"name": "Jeram C. Zamora", "email": "JeramC@phildata.com"},
    {"name": "Jhed Arevyne Pabanelas", "email": "JhedAP@phildata.com"},
    {"name": "John Paulo T. Barron", "email": "PauloTB@phildata.com"},
    {"name": "Lloyd Christian M. Ismael", "email": "LloydI@phildata.com"},
    {"name": "Marfelie B. Barcenas", "email": "MarfelieB@phildata.com"},
    {"name": "Marvin D. Garcia", "email": "VinG@phildata.com"},
    {"name": "Paul Gerald D. Buli", "email": "GeraldDB@phildata.com"},
    {"name": "Princess Nicole D. Nacianceno", "email": "PrincessDN@phildata.com"},
    {"name": "Royce Geronimo G. Cuizon", "email": "RoyceGC@phildata.com"},
    {"name": "Ryan Jay C. Mopal", "email": "RyanCM@phildata.com"},
    {"name": "William H. Tuazon", "email": "WilliamT@phildata.com"},
]

ENGINEER_NAMES = [engineer["name"] for engineer in ENGINEERS]


ACCOUNT_NAME_RAW = [
    "1AVIATION",
    "24/7 International",
    "3D Container and Packaging",
    "ACCRALAW",
    "ACSS",
    "Advanced World Systems, Inc.",
    "Aeon Credit",
    "Agile Technologies Inc.",
    "Aidea Inc.",
    "Aiful Corp",
    "AMPC",
    "AMWSLAI",
    "Araneta Group",
    "Asian Transmission Corp",
    "Atlas Fertilizer",
    "Bank of Makati",
    "BCC House",
    "Beltontotoku",
    "Benz Cy Enterprises Inc.",
    "BHAC",
    "Bicol Access Health Centrum",
    "Black & White Engineering",
    "Bridge Distribution Inc",
    "BroadCom",
    "Cargo bayan",
    "Carmelray Industrial Park",
    "Cashalo",
    "CEMEX Solid Cement",
    "Charoen PokPhand",
    "CHEQ",
    "China Bank",
    "CIBI",
    "CJ PHILIPPINES INC.",
    "Clark Development",
    "Classic Japan Ltd.",
    "Collins Aerospace",
    "COSD",
    "Crown Plaza/Holiday Inn",
    "CSD",
    "Cuadricom",
    "Cuadricom, Inc.",
    "Cura Property",
    "D&L Industries",
    "DCX",
    "Digital Network Communications",
    "Digits Trading Inc.",
    "Dimension All Manpower Inc.",
    "DLSMC",
    "Eastern Samar State University",
    "Eastvantage",
    "Eastwest Bank",
    "Easycall",
    "Easycall Communications Philippines",
    "Edward Marcs Phil., Inc.",
    "EIS",
    "Elite Global Phil., Inc.",
    "ENS",
    "Epson",
    "Eramen Mineral, Inc.",
    "ESG",
    "ESS",
    "Eton Properties Inc",
    "Exchange Equity Partners Group Corp.",
    "FAMI",
    "Famous Pacific",
    "FDCUI",
    "First Metro Insurance & Reinsurance Brokers, Inc.",
    "First Metro Sec",
    "First Metro Securities Brokerage Corp.",
    "First Sumiden Circuits",
    "FNG",
    "Forever Living Products Philippines Inc.",
    "FTECH",
    "Gardenia",
    "Genashtim Pte, Ltd.",
    "Genie X Technology",
    "Get Wonders Corporation",
    "GII Machinery and Equipment Services Inc.",
    "Global Cebuana",
    "Global Dominion",
    "Goodyear",
    "Greenbelt Residences",
    "GT Capital",
    "Health Alarm",
    "Homemark Inc.",
    "Howden Group",
    "HP Wolf/NIS2",
    "HPE",
    "HR",
    "Huawei",
    "ibex.",
    "IKEA",
    "Infineon",
    "Infinivan Inc.",
    "Infocom Asia Pacific Inc.",
    "Ingram Micro",
    "INTEGRATED WASTE MANAGEMENT INC.",
    "ISG",
    "JBA Philippines",
    "JGC Philippines Inc.",
    "JJED Phils., Inc.",
    "J-K Network Recruitment Services and Consultancy, Inc.",
    "Jolly Baybay",
    "Kansai Paint",
    "Korben Corp.",
    "KUS Holdings",
    "Kuysen Enterprises Inc.",
    "Kyocera",
    "LNP Credit Cooperative",
    "LWK",
    "Lynville Land Development Corporation",
    "Marquis Place",
    "Maxeon Solar Tech",
    "Maynilad",
    "MBTC",
    "MBTC P11",
    "MedEthix",
    "Megaworld",
    "Melters Steel Corp",
    "Metavers Information Technology Solutions",
    "MHI",
    "Microsoft",
    "MIS",
    "Mitsubishi Power",
    "Monde Nissin",
    "Mondelez Philippines",
    "MSG",
    "MTS Travel & Tours Services",
    "Nat Re",
    "New Media Services",
    "Nidec",
    "Nippon Premium Bakery",
    "Nippon Premium Bakery Inc.",
    "NTPHIL",
    "O-Healthcare Solution Phils, Inc.",
    "OLLH",
    "Olongapo City LGU",
    "OPTODEV",
    "Orix Metro",
    "Orix Metro Leasing and Finance Corporation",
    "Outsource BPO",
    "PA Properties",
    "PAL",
    "ParkPlace Technologies",
    "PAVI",
    "PD",
    "PDQC",
    "PGPC",
    "PGPG",
    "Phil-Data",
    "PHINMA Corporation",
    "PHPC",
    "Pilipinas Shell",
    "PKDF Marketing",
    "PLDT Tahanan",
    "PNB Holdings Corporation",
    "PPRC",
    "PressReaderPH",
    "Pricon",
    "Prime Asset Venture Inc.",
    "Prime Sales, Inc.",
    "PRPH",
    "PSBank",
    "Quantrics",
    "Raemulan",
    "Reliance Care Inc.",
    "RGO Laboratory",
    "Royal Duty Free",
    "Rudolf Lietz, Inc.",
    "Sagility",
    "Sales",
    "SAT-A",
    "SDP Access",
    "SEMPHIL",
    "Sinag Pawnshop",
    "SLMC",
    "SMC",
    "SMCQC",
    "SMIC",
    "SMLC",
    "Sohbi Kohgei, Inc.",
    "Solaire Resort",
    "Solar Wind",
    "SPC Power Corporation",
    "St. Mary College of Quezon City",
    "St. Mary's Academy of Caloocan",
    "St. Mary's Academy of Tagoloan",
    "Standard Insurance",
    "Stradcom",
    "Straive",
    "SunTrust",
    "Support Ninja",
    "Taft Properties",
    "Tagaytay Medical Center",
    "Talentium",
    "TaskUs",
    "TECHBOX INTERNATIONAL INC",
    "Technolux",
    "TFS1",
    "The Residences at Greenbelt Condominium Corporation",
    "Tomoike",
    "Tong Lung",
    "Touchcore Solution Inc.",
    "TFS",
    "Toyota Financial Services",
    "Travelers Hotel SBMA",
    "Travellers International Hotel Group, Inc.",
    "Trigon Management and Industrial Corporation",
    "Ubidy Pty Ltd",
    "Ubiquity",
    "Unilever",
    "Universal Hotels",
    "University of Cebu",
    "University of Rhode Island- Philippine Branch",
    "VacuumTech Philippines Inc.",
    "Veeam",
    "Vertex Entertainment",
    "VMware",
    "VST",
    "Weigand and Partners",
    "Whiteport Inc.",
    "Wills International Sales Corp",
    "WSLAI",
    "East Negros Health Alliance Inc.",
    "Otsuka",
    "Otsuka Philippines Pharmaceutical, Inc.",
    "Andoks",
    "GLOBAL DOMINION FINANCING INC.",
    "NITYO INFOTECH INC.",
    "SULO CREATIVES OPC",
    "Nustar Resort & Casino, UHRI",
    "TELUS INTERNATIONAL PHILIPPINES, INC.",
    "SENCO",
    "Sovrun",
    "Palm Concepcion Power Concepcion",
    "Club 3 Asia Projects Inc",
    "Level 3 IT Solutions",
    "JARC GROUP",
    "BCC CAT",
    "Global Officium",
    "SonicWall",
    "REX",
    "Consistent Frozen Solutions",
    "Venice 66 Fashions Inc.",
    "SharePro",
    "Global Virtuoso",
    "Ayala Multi-Purpose Cooperative",
    "Executive Optical Inc.",
    "Fibernet Konstrukt Corp",
    "Fort Bonifacio Global",
    "Amaco Inc.",
    "Panasonic",
    "Vans PH",
    "Riverside College",
    "Riverside College Inc",
    "Vertere GS",
    "Mabuhay Energy",
    "DOH",
    "CCTV",
    "Hardware",
    "CIBO",
    "Ruckus",
    "Teligent",
    "DCCD",
    "Bhagi International Trading",
    "Swedish Match Lights",
    "TransUnion",
    "Dell",
    "HP",
    "Kharla Fortich",
    "Bhagi's Internation Trading",
    "Viking's",
    "Brother Industries",
    "Manupali",
    "SGL",
    "Scan Global",
    "Soliman",
    "Soliman Security Services Inc.",
    "CVM Pawnshop",
    "Outsight",
]

ACCOUNT_NAME_SUGGESTIONS = tuple(dict.fromkeys(name.strip() for name in ACCOUNT_NAME_RAW if name and name.strip()))
