from django.urls import path
from django.views.generic import RedirectView

from .views import (
    DashboardView,
    EngineerActivityLogView,
    NotificationListView,
    NotificationFollowRedirectView,
    NotificationReadView,
    NotificationDeleteView,
    NotificationMarkAllReadView,
    RequestAdminUpdateView,
    RequestDeleteView,
    RequestRestoreView,
    RequestExportCSVView,
    RequestNudgeView,
    RequestOutlookRedirectView,
    RequestClosingOutlookRedirectView,
    EngineerActivityLogDeleteView,
    RequestStatusUpdateView,
    RequestTeamsRedirectView,
    RequestUpdateView,
    RequestReportView,
    ReportExportView,
    SqrListView,
    SqrDeliveryUpdateView,
    SqrToRevenueView,
    SqrEngineerDeleteView,
    SqrEngineerUpdateView,
    SqrImportView,
    SqrProposalUpdateView,
    SqrInlineFieldUpdateView,
    SqrRevenueTrackerUpdateView,
    SqrRevenueUpdateView,
    SqrTeamsRedirectView,
    SqrApprovalOutlookRedirectView,
    SqrApprovalEmlDownloadView,
    SqrReviewUpdateView,
    SqrExportView,
    StatusLogUpdateView,
    UserEditView,
    UserManagementView,
    RequestCollaborativeManageView,
)

app_name = "hub"

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("activity-logs/", EngineerActivityLogView.as_view(), name="activity-logs"),
    path("activity-logs/<int:pk>/delete/", EngineerActivityLogDeleteView.as_view(), name="activity-log-delete"),
    path("requests/export/csv/", RequestExportCSVView.as_view(), name="request-export"),
    path("requests/<int:pk>/", RedirectView.as_view(pattern_name="hub:request-manage-collab", permanent=True), name="request-detail"),
    path("requests/<int:pk>/edit/", RequestUpdateView.as_view(), name="request-edit"),
    path("requests/<int:pk>/status/", RequestStatusUpdateView.as_view(), name="request-status"),
    path("requests/<int:pk>/manage/", RequestAdminUpdateView.as_view(), name="request-manage"),
    path("requests/<int:pk>/manage/collab/", RequestCollaborativeManageView.as_view(), name="request-manage-collab"),
    path("status-logs/<int:pk>/edit/", StatusLogUpdateView.as_view(), name="status-log-edit"),
    path("requests/<int:pk>/nudge/", RequestNudgeView.as_view(), name="request-nudge"),
    path("requests/<int:pk>/teams-chat/", RequestTeamsRedirectView.as_view(), name="request-teams"),
    path("requests/<int:pk>/outlook/", RequestOutlookRedirectView.as_view(), name="request-outlook"),
    path("requests/<int:pk>/outlook/closing/", RequestClosingOutlookRedirectView.as_view(), name="request-outlook-closing"),
    path("requests/<int:pk>/delete/", RequestDeleteView.as_view(), name="request-delete"),
    path("requests/<int:pk>/restore/", RequestRestoreView.as_view(), name="request-restore"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view(), name="notification-read"),
    path("notifications/<int:pk>/follow/", NotificationFollowRedirectView.as_view(), name="notification-follow"),
    path("notifications/<int:pk>/delete/", NotificationDeleteView.as_view(), name="notification-delete"),
    path("notifications/mark-all-read/", NotificationMarkAllReadView.as_view(), name="notification-mark-all-read"),
    path("sqr/", SqrListView.as_view(), name="sqr"),
    path("sqr/export/", SqrExportView.as_view(), name="sqr-export"),
    path("sqr/import/", SqrImportView.as_view(), name="sqr-import"),
    path("sqr/import/status/", SqrImportView.as_view(), name="sqr-import-status"),
    path("sqr/<int:pk>/edit/", SqrEngineerUpdateView.as_view(), name="sqr-edit"),
    path("sqr/<int:pk>/inline-update/", SqrInlineFieldUpdateView.as_view(), name="sqr-inline-update"),
    path("sqr/<int:pk>/delete/", SqrEngineerDeleteView.as_view(), name="sqr-delete"),
    path("sqr/<int:pk>/revenue-tracker/", SqrRevenueTrackerUpdateView.as_view(), name="sqr-revenue-update"),
    path("sqr/<int:pk>/proposal/", SqrProposalUpdateView.as_view(), name="sqr-proposal-update"),
    path("sqr/<int:pk>/delivery/", SqrDeliveryUpdateView.as_view(), name="sqr-delivery-update"),
    path("sqr/<int:pk>/to-revenue/", SqrToRevenueView.as_view(), name="sqr-to-revenue"),
    path("sqr/<int:pk>/revenue/", SqrRevenueUpdateView.as_view(), name="sqr-revenue-stage-update"),
    path("sqr/<int:pk>/teams/", SqrTeamsRedirectView.as_view(), name="sqr-teams"),
    path("sqr/<int:pk>/approval-email/", SqrApprovalOutlookRedirectView.as_view(), name="sqr-approval-email"),
    path("sqr/<int:pk>/approval-email/eml/", SqrApprovalEmlDownloadView.as_view(), name="sqr-approval-email-eml"),
    path("sqr/<int:pk>/review/", SqrReviewUpdateView.as_view(), name="sqr-review"),
    path("management/", UserManagementView.as_view(), name="management"),
    path("users/<int:pk>/manage/", UserEditView.as_view(), name="user-edit"),
    path("reports/", RequestReportView.as_view(), name="report"),
    path("reports/export/", ReportExportView.as_view(), name="report-export"),
]
